fix downstream tests

diff --git a/.github/workflows/knative-downstream.yaml b/.github/workflows/knative-downstream.yaml
--- a/.github/workflows/knative-downstream.yaml
+++ b/.github/workflows/knative-downstream.yaml
@@ -16,90 +16,65 @@ name: Downstream
 
 on:
   pull_request:
-    branches: [ 'main', 'master', 'release-*' ]
+    branches: [ 'main', 'release-*' ]
 
 jobs:
-
   downstream-knative:
-    name: knative-${{ matrix.repository }}
+
+    name: Unit Test
+    runs-on: ubuntu-latest
+
     strategy:
+      fail-fast: false # Keep running if one leg fails.
       matrix:
-        go-version: [1.18.x]
-        platform: [ubuntu-latest]
-        repository: [serving]
-
-    runs-on: ${{ matrix.platform }}
-
-    env:
-      GOPATH: ${{ github.workspace }}
+        repo:
+        - knative/serving
+        - knative-sandbox/net-contour
+        - knative-sandbox/net-istio
+        - knative-sandbox/net-kourier
+        - knative-sandbox/net-certmanager
+        - knative-sandbox/net-http01
 
     steps:
-
-    - name: Set up Go ${{ matrix.go-version }}
-      uses: actions/setup-go@v2
+    - name: Set up Go 1.18.x
+      uses: actions/setup-go@v3
       with:
-        go-version: ${{ matrix.go-version }}
-      id: go
+        go-version: 1.18.x
 
     - name: Install Dependencies
       run: |
         go install github.com/google/go-licenses@latest
 
-    - name: Checkout Upstream
-      uses: actions/checkout@v2
+    - name: Checkout upstream at ${{ github.base_ref }}
+      uses: actions/checkout@v3
       with:
-        path: ./src/knative.dev/${{ github.event.repository.name }}
+        fetch-depth: 0
+        path: upstream
 
-    - name: Checkout Downstream
-      uses: actions/checkout@v2
-      with:
-        repository: knative/${{ matrix.repository }}
-        path: ./src/knative.dev/${{ matrix.repository }}
-
-    - name: Test Downstream
-      uses: knative-sandbox/downstream-test-go@v1.0.1
-      with:
-        upstream-module: knative.dev/${{ github.event.repository.name }}
-        downstream-module: knative.dev/${{ matrix.repository }}
-
-  downstream-knative-sandbox:
-    name: knative-sandbox-${{ matrix.repository }}
-    strategy:
-      matrix:
-        go-version: [1.18.x]
-        platform: [ubuntu-latest]
-        repository: [net-istio, net-contour, net-kourier, net-certmanager, net-http01]
-
-    runs-on: ${{ matrix.platform }}
-
-    env:
-      GOPATH: ${{ github.workspace }}
-
-    steps:
-
-    - name: Set up Go ${{ matrix.go-version }}
-      uses: actions/setup-go@v2
-      with:
-        go-version: ${{ matrix.go-version }}
-      id: go
-
-    - name: Install Dependencies
+    - name: Merge upstream
+      if: github.event_name == 'pull_request'
+      shell: bash
+      working-directory: upstream
       run: |
-        go install github.com/google/go-licenses@latest
+         if ! git config user.name > /dev/null; then
+           git config user.name "Knative Action"
+         fi
+         if ! git config user.email > /dev/null; then
+           git config user.email "action@knative.dev"
+         fi
+         git remote add upstream https://github.com/${{ github.repository }}.git
+         git fetch upstream ${{ github.base_ref }}
+         git pull --no-rebase --no-commit upstream ${{ github.base_ref }}
 
-    - name: Checkout Upstream
-      uses: actions/checkout@v2
+    - name: Checkout downstream at ${{ github.base_ref }}
+      uses: actions/checkout@v3
       with:
-        path: ./src/knative.dev/${{ github.event.repository.name }}
+        ref: ${{ github.base_ref }}
+        repository: ${{ matrix.repo }}
+        path: downstream
 
-    - name: Checkout Downstream
-      uses: actions/checkout@v2
+    - name: Test downstream
+      uses: knative/actions/go/downstream-test@main
       with:
-        repository: knative-sandbox/${{ matrix.repository }}
-        path: ./src/knative.dev/${{ matrix.repository }}
-
-    - name: Test Downstream
-      uses: knative-sandbox/actions-downstream-test@v1
-      with:
-        upstream-module: knative.dev/${{ github.event.repository.name }}
-        downstream-module: knative.dev/${{ matrix.repository }}
+        upstream-path: upstream
+        downstream-path: downstream
